database:
  type: SQLite
  url: "test.db"
  username:
  password:
keycloak:
  client_id: "admin-cli"
  realm: "throwback-art"
  host: "http://containers.burgerspace.net:44929"
  client_secret: "daJ4H8j7mg3rIAYb67Zfq9P11e21MQOy"