services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    volumes:
      - ../keycloak/throwback-keycloak-listener/target/throwback-listener.jar:/opt/keycloak/providers/throwback-listener.jar
      - ${LOCALHOST_KEY}:/opt/keycloak/ssl/private.key
      - ${LOCALHOST_CERT}:/opt/keycloak/ssl/public.crt
    environment:
      KC_LOG_LEVEL: info
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_SCHEMA: ${KC_DB_SCHEMA}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HOSTNAME_STRICT: true
      HTTP_ADDRESS_FORWARDING: false
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      THROWBACK_API_URL: ${THROWBACK_API_URL}
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/ssl/private.key
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/ssl/public.crt
    command:  start-dev
    ports:
      - '8080:8080' #HTTP
      - '8443:8443' #HTTPS
  keycloakdb:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_USERNAME}
  minio:
    image: quay.io/minio/minio:RELEASE.2024-06-06T09-36-42Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" #API
      - "9001:9001" #ADMIN
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    hostname: localhost
    volumes:
      - minio_data:/data
      - ${LOCALHOST_KEY}:/root/.minio/certs/private.key
      - ${LOCALHOST_CERT}:/root/.minio/certs/public.crt
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      discovery.type: single-node
      node.name: opensearch
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD_ENV}
    volumes:
      - opensearch_data:/usr/share/opensearch/data
      #Only do this if you want to change the admin password
      #This should never be commited
      - ../opensearch/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - opensearch-net
    depends_on:
      - opensearch
volumes:
  postgres_data:
  minio_data:
  opensearch_data:

networks:
  opensearch-net:
    driver: bridge