services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    volumes:
      - ../keycloak/throwback-keycloak-listener/target/throwback-listener.jar:/opt/keycloak/providers/throwback-listener.jar
      - ${LOCALHOST_KEY}:/opt/keycloak/ssl/private.key
      - ${LOCALHOST_CERT}:/opt/keycloak/ssl/public.crt
    environment:
      DISCOURSE_API_SERVICE_USERNAME: ${DISCOURSE_API_SERVICE_USERNAME}
      KC_LOG_LEVEL: info
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_SCHEMA: ${KC_DB_SCHEMA}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT_HTTPS: true
      KC_HOSTNAME_STRICT: true
      HTTP_ADDRESS_FORWARDING: false
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      NOBOT_API_URL: ${NOBOT_API_URL}
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/ssl/private.key
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/ssl/public.crt
      KEYCLOAK_TO_NOBOT_API_ACCESS_TOKEN: ${KEYCLOAK_TO_NOBOT_API_ACCESS_TOKEN}
    command:  start-dev
    ports:
      - '8080:8080' #HTTP
      - '8443:8443' #HTTPS
    extra_hosts:
      - "localhost:172.17.0.1"
  keycloakdb:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_USERNAME}
  nobotdb:
    image: postgres:16
    volumes:
      - postgres_nobot_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${NOBOT_DB_NAME}
      POSTGRES_USER: ${NOBOT_DB_USERNAME}
      POSTGRES_PASSWORD: ${NOBOT_DB_USERNAME}
    ports:
      - "54382:5432"
  #This is left behind for legacy testing with minio uncomment it and the volume to run minio
  #minio:
  #  image: quay.io/minio/minio:RELEASE.2024-06-06T09-36-42Z
  #  command: server /data --console-address ":9001"
  #  ports:
  #    - "9000:9000" #API
  #    - "9001:9001" #ADMIN
  #  environment:
  #    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  #    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  #  hostname: localhost
  #  volumes:
  #    - minio_data:/data
  #    - ${LOCALHOST_KEY}:/root/.minio/certs/private.key
  #    - ${LOCALHOST_CERT}:/root/.minio/certs/public.crt
volumes:
  postgres_data:
  postgres_nobot_data:
  #minio_data:
