database:
  type: SQLite
  url: "../../test.db"
  username:
  password:
keycloak:
  jwks_uri: "https://localhost:8443/realms/throwback-art/protocol/openid-connect/certs"
  client-id: "throwback-spa"
s3:
  url: "localhost:9000"
  bucket: "main"
  secret: "E6RDLAw1BNTB85nNDxCIKcfa0M4AGGOVj1hnIt5x"
  access: "K9uxBVsC8Fey6ZqNgzU0"
